<ol class="breadcrumb mb-2 mt-2">
    <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="/usuarios">Usuários</a></li>
    <li class="breadcrumb-item active">Cadastro Usuários</li>
</ol>

<!-- Formulário -->
<div class="card shadow">
    <div class="card-header">
        <h6>Cadastro Usuário</h6>
    </div>
    <div class="card-body">
        <form method="post" action="/registrar">
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    <label for="validationDefault01">Nome </label>
                    <input type="text" name="nome" value="<?= $this->view->usuario['nome'] ?>" class="form-control form-control-sm shadow-sm rounded-pill" id="validationDefault01" placeholder="Nome" required>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationDefault02">Login</label>
                    <input type="text" name="login" value="<?= $this->view->usuario['login'] ?>" class="form-control form-control-sm shadow-sm rounded-pill" id="validationDefault02" placeholder="Usuário" required>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="validationDefaultUsername">E-mail</label>
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend2">@</span>
                        </div>
                        <input type="text" name="email" value="<?= $this->view->usuario['email'] ?>" class="form-control form-control-sm shadow-sm rounded-pill" id="validationDefaultUsername" placeholder="E-mail" aria-describedby="inputGroupPrepend2" required>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-3 mb-3">
                    <label for="validationDefault03">Senha</label>
                    <input type="password" name="senha" value="<?= $this->view->usuario['senha'] ?>" class="form-control form-control-sm shadow-sm rounded-pill" id="validationDefault03" placeholder="Senha" required>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationDefault04">Tipo</label>
                    <select name="id_tipo" class="custom-select custom-select-sm shadow-sm rounded-pill" required>
                        <option selected value="<?php echo $this->view->usuario['id_tipo'] ?>">...</option>
                        <?php foreach ($this->view->tipo_user as $key => $value) { ?>
                            <option value=" <?php echo $value['id'] ?>"><?= $value['descricao'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="validationDefault04">Loja</label>
                    <select name="id_loja" class="custom-select custom-select-sm shadow-sm rounded-pill" required>
                        <option selected value="">...</option>
                        <?php foreach ($this->view->lojas as $key => $value) { ?>
                            <option value=" <?php echo $value['id_loja'] ?>"><?= $value['local'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-sm btn-success shadow-sm rounded-pill float-right">Salvar</button>
            <?php if ($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">Erro ao relizae cadastro, verifique se os campos foram preenchidos corretameten.</small>
            <?php } ?>
        </form>
    </div>
</div>