  <ol class="breadcrumb mb-2 mt-2">
      <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
      <li class="breadcrumb-item active">Clientes</li>
  </ol>


  <div class="card-body shadow bg-light rounded mb-2">
      <div class="card-header bg-light">
          <a href="/cadastro_cliente" class="m-2 btn btn-sm btn-success rounded-pill shadow-sm float-lg-right" data-toggle="tooltip" data-placement="top" title="Adicionar Novo Cliente"><i class=" fa fa-plus-circle"></i> Novo Cliente</a>
          <h4>Clientes </h4>
      </div>
      <div class="data-table-area mt-3">
          <div class="data-table-list bg-light rounded">
              <div class="table-responsive">
                  <table class=" table table-sm table-responsive-sm table-hover rounded" id="data-table-basic">
                      <thead class="">
                          <tr class="">
                              <th scope="col">Nome</th>
                              <th scope="col">CPF</th>
                              <th scope="col">E-mail</th>
                              <th scope="col">Telefone</th>
                              <th scope="col">loja</th>
                              <th scope="col">Data cadastro</th>
                              <th scope="col">Ação</th>
                          </tr>
                      </thead>


                      <tbody>
                          <?php foreach ($this->view->dados as $key => $value) { ?>

                              <tr>
                                  <td style="text-transform: uppercase;"><?php echo $value['nome'] ?></td>
                                  <td><?php echo $value['cpf'] ?></td>
                                  <td>
                                      <?php
                                        if ($value['email'] == '') {
                                            echo ("Não possui E-mail");
                                        } else {
                                            echo $value['email'];
                                        }
                                        ?>
                                  </td>
                                  <td><?php echo $value['telefone'] ?></td>
                                  <td style="text-transform: uppercase;"><?php echo $value['local'] ?></td>
                                  <td><?php echo $value['data_cadastro'] ?></td>
                                  <td><a class=" btn btn-blue btn-sm rounded-pill shadow-sm" data-toggle="tooltip" data-placement="top" title="Ver Dados do Cliente" href=" /detalhe_cliente?id=<?= $value['id'] ?>"><i class=""></i>Abrir</a>
                              </tr>
                          <?php } ?>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>

  <script>

  </script>