<!-- page content -->
<ol class="breadcrumb mb-2 mt-2">
    <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="/cliente">Clientes</a></li>
    <li class="breadcrumb-item active">Dados do Cliente</li>
</ol>

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="card shadow p-3 m-3">
            <div class="card-header">
                <h3>Dados do Cliente</h3>
            </div>
            <div class="card-body p-3 bg-white rounded">
                <div class="pull-left">
                    <?php foreach ($this->view->cadCliente as $key => $value) { ?>
                        <h4 class="text-info"><?php echo $value['nome'] ?></h4>
                        <ul class="">
                            <li><i class=" user-profile-icon"></i>
                                CPF: <?php echo $value['cpf'] ?>
                            </li>
                            <li><i class="fa fa-map-marker user-profile-icon"></i>
                                Endereço: <?= $value['rua'] ?>,
                                <?php echo $value['numero'] ?>,
                                <?php echo $value['bairro'] ?>,
                                <?php echo $value['cidade'] ?> -
                                <?php echo $value['uf'] ?>
                            </li>
                            <li>
                                <i class="fa fa-phone user-profile-icon"></i> Telefone: <?php echo $value['telefone'] ?>
                            </li>
                            <li>
                                <i class="fa fa-envelope user-profile-icon"></i> E-mail: <?php echo $value['email'] ?>
                            </li>
                            <li>
                                <i class="fa fa-shopping-cart user-profile-icon"></i> Loja: <?php echo $value['nome_loja'] ?> - ( <?php echo $value['local'] ?> )
                            </li>
                            <li>
                                <i class="fa fa-calendar user-profile-icon"></i> Data do cadastro: <?php echo $value['data_cadastro'] ?>
                            </li>
                        </ul>
                        <i class=" btn btn-sm btn-outline-primary rounded-pill shadow-sm fa fa-edit m-right-xs" data-toggle="modal" data-target="#exampleModal"> Editar</i>
                        <br />

                    <?php } ?>
                </div>
                <div class=" pull-right ">

                    <div class="col-md-12 col-sm-12 m-4 p-3 ">
                        <h3>Compras por Loja </h3>
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Loja</th>
                                    <th scope="col">Qtd. Pedidos</th>
                                    <th scope="col">Valor Total </th>


                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->view->detalhe_valor as $key => $value) { ?>
                                    <tr>
                                        <th scope="row"><?php echo $value['local'] ?></th>
                                        <td><?php echo $value['qt_total_pedido'] ?></td>
                                        <td>R$ <?php
                                                $valor_total = str_replace(".", ",",  $value['valor_total']);
                                                if (strlen($valor_total) < 7) {
                                                    echo $valor_total;
                                                } else {
                                                    echo substr_replace($valor_total, '.', -6, 0);
                                                }
                                                ?>
                                        </td>

                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1 col-sm-1 m-2 float-right">
            <a type="button" class="btn btn-sm btn-blue rounded-pill shadow-sm float-right" href="/cliente">Voltar</a>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-info" id="exampleModalLabel"> Atualizar Dados do Cliente</h5>
                <h5 class=" text-info glyphicon glyphicon-pencil ml-5"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="/atualizar_cliente" class="needs-validation" novalidate>
                    <div class="form-row">
                        <div class="col-md-5 mb-3">
                            <label for="validationCustom01">Nome Completo</label>
                            <input name="nome" value="<?php echo $this->view->cadCliente[0]['nome'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" required>
                            <input name="id" value="<?php echo $_GET['id'] ?>" type="text" class="form-control" hidden>
                            <div class="valid-feedback">
                                Tudo certo!
                            </div>
                        </div>
                        <div class="col-md-5 mb-3">
                            <label for="validationCustom02">E-mail</label>
                            <input name="email" value="<?php echo $this->view->cadCliente[0]['email'] ?>" type=" email" class="form-control form-control-sm rounded-pill shadow-sm">
                            <div class="valid-feedback">
                                Tudo certo!
                            </div>
                        </div>
                        <div class="col-md-2 mb-3">
                            <label for="validationCustom03">CPF</label>
                            <input name="cpf" value="<?php echo $this->view->cadCliente[0]['cpf'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" required>
                            <div class="valid-feedback">
                                Tudo certo!
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="validationCustom04">Telefone</label>
                            <input name="telefone" value="<?php echo $this->view->cadCliente[0]['telefone'] ?>" type=" tel" class="form-control form-control-sm rounded-pill shadow-sm" required>
                            <div class="valid-feedback">
                                Tudo certo!
                            </div>
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="validationCustom05">Tipo Telefone</label>
                            <select name="tipo" class="custom-select custom-select-sm rounded-pill shadow-sm" required>
                                <option selected value="<?php echo $this->view->cadCliente[0]['tipo'] ?>"><?php echo $this->view->cadCliente[0]['tipo'] ?></option>
                                <option value="CEL">Celular</option>
                                <option value="RES">Residencial</option>
                                <option value="COM">Comercial</option>
                            </select>
                        </div>

                        <div class="col-md-4 mb-3">
                            <label for="validationCustom06">Loja</label>
                            <select name="id_loja" class="custom-select custom-select-sm rounded-pill shadow-sm" required>
                                <option selected value="<?php echo $this->view->cadCliente[0]['id_loja'] ?>"><?php echo $this->view->cadCliente[0]['local'] ?></option>
                                <?php foreach ($this->view->lojas as $key => $value) { ?>
                                    <option value="<?php echo $value['id_loja'] ?>"><?php echo $value['local'] ?></option>
                                <?php } ?>
                            </select>

                            <div class="valid-feedback">
                                Tudo certo!
                            </div>
                        </div>
                    </div>

                    <div class="container">
                        <div class="row form-group">
                            <div class="col-sm-2">
                                <label class="form-check-label" for="invalidCheck">CEP</label>
                                <input name="cep" value="<?php echo $this->view->cadCliente[0]['cep'] ?>" type=" number" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="CEP" onblur="getDadosEnderecoPorCEP(this.value)" required />
                            </div>
                            <div class="col-sm-4">
                                <label class="form-check-label" for="invalidCheck">Logradouro</label>
                                <input name="rua" value="<?php echo $this->view->cadCliente[0]['rua'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="Logradouro" id="endereco" required />
                            </div>
                            <div class="col-sm-5">
                                <label class="form-check-label" for="invalidCheck">Referência</label>
                                <input name="referencia" value="<?php echo $this->view->cadCliente[0]['referencia'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="Referecia" id="endereco" />
                            </div>
                            <div class="col-sm-1">
                                <label class="form-check-label" for="invalidCheck">Nº</label>
                                <input name="numero" value="<?php echo $this->view->cadCliente[0]['numero'] ?>" type=" number" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="Nº 99999" />
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-sm-6">
                                <label class="form-check-label" for="invalidCheck">Bairro</label>
                                <input name="bairro" value="<?php echo $this->view->cadCliente[0]['bairro'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="Bairro" id="bairro" required />
                            </div>
                            <div class="col-sm-4">
                                <label class="form-check-label" for="invalidCheck">Cidade</label>
                                <input name="cidade" value="<?php echo $this->view->cadCliente[0]['cidade'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="Cidade" id="cidade" />
                            </div>

                            <div class="col-sm-2">
                                <label class="form-check-label" for="invalidCheck">Estado</label>
                                <input name="uf" value="<?php echo $this->view->cadCliente[0]['uf'] ?>" type=" text" class="form-control form-control-sm rounded-pill shadow-sm" placeholder="UF" id="uf" />
                            </div>
                        </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-outline-secondary rounded-pill shadow-sm" data-dismiss="modal">Sair sem Salvar</button>
                <button type="submit" class="btn btn-sm btn-outline-success rounded-pill shadow-sm">Salvar</button>
            </div>
            </form>
        </div>
    </div>
</div>


<!-- /page content -->