<ol class="breadcrumb mb-1 mt-1">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
<div class="col-md-12 col-sm-12 p-2 mb-2 shadow-sm bg-light rounded">
    <div class="col-md-5 col-sm-5">
        <h4>Filtro</h4>
    </div>

    <form id="form" action="/search_home" method="get">

        <div class="form-row">
            <div class="form-group col-md-3 col-sm-3">
                <label for="validationCustom01">Data Inicial</label>
                <input name="data_inicial" value="" type="date" class="form-control form-control-sm rounded-pill" required>
            </div>
            <div class="form-group col-md-3 col-sm-3">
                <label for="validationCustom02">Data Final</label>
                <input name="data_final" value="" type="date" class="form-control form-control-sm rounded-pill" required>
            </div>
            <div class="form-group col-md-2 col-sm-2">
                <div id="select_loja" style="display: block;">
                    <label for="validationCustom03">Loja </label>
                    <select name="id_loja" class="custom-select custom-select-sm rounded-pill">
                        <option value="">...</option>
                        <?php foreach ($this->view->lista_loja as $key => $value) { ?>
                            <option value="<?php echo $value['id'] ?>"><?php echo $value['local'] ?></option>
                        <?php } ?>
                    </select>
                    <div class="valid-feedback">
                        Tudo certo!
                    </div>
                </div>
            </div>
            <div class="form-group col-md-2 col-sm-2">
                <div class="form-check form-check-sm">
                    <div class="onoff">
                        <h6>Todas as Lojas</h6>
                        <input type="checkbox" class="toggle" id="onoff1" onclick="mostrar('select_loja')" />
                        <label for="onoff1"></label>
                    </div>

                </div>
            </div>
            <div class="col-md-2 col-sm-2">
                <label>
                    <h6></h6>
                    <button class="btn btn-sm btn-outline-success shadow-sm rounded-pill" type="submit"><a class="fa fa-check"></a> Aplicar Filtro</button>
                </label>
            </div>
        </div>
    </form>
</div>

<div class="col-md-12 col-sm-12 mb-1 p-2 rounded bg-light">
    <!-- Widgets  -->
    <div class="row mt-3">
        <div class="col-lg-3 col-md-6">
            <div class="card shadow mb-1 border-left-01">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-1">
                            <i class="pe-7s-cash"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left display-iline-block">
                                <div class="stat-text">R$<span>
                                        <?php foreach ($this->view->dados_dia as $key => $value) { ?>
                                            <?php
                                            $valor_dia = str_replace(".", ",",  $value['valor_dia']);
                                            if (strlen($valor_dia) < 7) {
                                                echo $valor_dia;
                                            } else if (strlen($valor_dia) <= 9) {
                                                echo substr_replace($valor_dia, '.', -6, 0);
                                            } else if (strlen($valor_dia) > 9) {
                                                $val_dia = substr_replace($valor_dia, '.', -6, 0);
                                                echo substr_replace($val_dia, '.', -10, 0);
                                            }
                                            ?>
                                        <?php } ?>
                                    </span></div>
                                <div class="stat-heading">
                                    Valor:
                                    <?php
                                    echo utf8_encode(gmstrftime('%d de %B de %Y'));
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow mb-1 border-left-02">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon flat-color-2">
                            <i class="pe-7s-cart"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left display-iline-block">
                                <div class="stat-text"><span class="count">
                                        <?php foreach ($this->view->dados_dia as $key => $value) { ?>
                                            <?php echo $value['qt_pedido_dia'] ?>
                                        <?php } ?>
                                    </span></div>
                                <div class="stat-heading">
                                    Pedidos:
                                    <?php
                                    echo utf8_encode(gmstrftime('%d de %B de %Y'));
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow mb-1 border-left-03">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon flat-color-1">
                            <i class="ti-money"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left display-iline-block">
                                <div class="stat-text">R$<span>

                                        <?php foreach ($this->view->dados_dia as $key => $value) { ?>
                                            <?php
                                            $media_dia = str_replace(".", ",",  $value['media_dia']);
                                            if (strlen($media_dia) < 7) {
                                                echo $media_dia;
                                            } else if (strlen($media_dia) <= 9) {
                                                echo substr_replace($media_dia, '.', -6, 0);
                                            } else if (strlen($media_dia) > 9) {
                                                $med_dia = substr_replace($media_dia, '.', -6, 0);
                                                echo substr_replace($med_dia, '.', -10, 0);
                                            }
                                            ?>
                                        <?php } ?>
                                    </span>
                                </div>
                                <div class="stat-heading">
                                    Média:
                                    <?php
                                    echo utf8_encode(gmstrftime('%d de %B de %Y'));
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="card shadow mb-1 border-left-04">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon flat-color-4">
                            <i class="pe-7s-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left display-iline-block">
                                <div class="stat-text"><span class="count">
                                        <?php foreach ($this->view->dados_dia as $key => $value) { ?>
                                            <?php echo $value['qt_cliente'] ?>
                                        <?php } ?>

                                    </span></div>
                                <div class="stat-heading">
                                    Clientes:
                                    <?php
                                    echo utf8_encode(gmstrftime('%d de %B de %Y'));
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-3 col-md-6">
            <div class="card text-white bg-flat-color-1 shadow mb-1">
                <div class="card-body">
                    <?php foreach ($this->view->valor_mes as $key => $value) { ?>
                        <div class="card-left pt-1 float-left">
                            <h3 class="mb-0 fw-r">
                                <span class="currency float-left mr-1">$</span>
                                <span>
                                    <?php
                                    $valor_mes = str_replace(".", ",",  $value['valor_mes']);
                                    if (strlen($valor_mes) < 7) {
                                        echo $valor_mes;
                                    } else if (strlen($valor_mes) <= 9) {
                                        echo substr_replace($valor_mes, '.', -6, 0);
                                    } else if (strlen($valor_mes) > 9) {
                                        $val_mes = substr_replace($valor_mes, '.', -6, 0);
                                        echo substr_replace($val_mes, '.', -10, 0);
                                    }
                                    ?>
                                </span>
                            </h3>
                            <p class="text-light mt-1 m-0">Valor Mês:
                                <?php //echo $value['mes'];
                                echo utf8_encode(gmstrftime('%B de %Y'));

                                ?>
                            </p>
                        </div>
                    <?php } ?> <div class="card-right float-right text-right">
                        <i class="icon fade-5 icon-md pe-7s-cash"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card text-white bg-flat-color-2 shadow mb-1">
                <div class="card-body">
                    <?php foreach ($this->view->valor_mes as $key => $value) { ?>
                        <div class="card-left pt-1 float-left">
                            <h3 class="mb-0 fw-r">
                                <span class="currency float-left mr-1"></span>
                                <span class="count">
                                    <?php echo $value['qt_pedido_mes'] ?>
                                </span>
                            </h3>
                            <p class="text-light mt-1 m-0">Pedidos Mês:
                                <?php //echo $value['mes'];
                                echo utf8_encode(gmstrftime('%B de %Y'));
                                ?>
                            </p>
                        </div>
                    <?php } ?>
                    <div class="card-right float-right text-right">
                        <i class="icon fade-5 icon-md pe-7s-cart"></i>
                    </div><!-- /.card-right -->
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card text-white bg-flat-color-3 shadow mb-1">
                <div class="card-body">
                    <div class="card-left pt-1 float-left">
                        <?php foreach ($this->view->valor_mes as $key => $value) { ?>
                            <h3 class="mb-0 fw-r">
                                <span class="currency float-left mr-1">$</span>
                                <span>
                                    <?php
                                    $media_mes = str_replace(".", ",",  $value['media_mes']);
                                    if (strlen($media_mes) < 7) {
                                        echo $media_mes;
                                    } else if (strlen($media_mes) <= 9) {
                                        echo substr_replace($media_mes, '.', -6, 0);
                                    } else if (strlen($media_mes) > 9) {
                                        $med_mes = substr_replace($media_mes, '.', -6, 0);
                                        echo substr_replace($med_mes, '.', -10, 0);
                                    }
                                    ?>
                                </span>
                            </h3>
                            <p class="text-light mt-1 m-0">Média Mês:
                                <?php //echo $value['mes'];
                                echo utf8_encode(gmstrftime('%B de %Y'));
                                ?>
                            </p>
                    </div>
                <?php } ?>
                <div class="card-right float-right text-right">
                    <i class="icon fade-5 icon-md ti-money"></i>
                </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card text-white bg-flat-color-4 shadow mb-1">
                <div class="card-body">
                    <div class="card-left pt-1 float-left">
                        <h3 class="mb-0 fw-r">
                            <?php foreach ($this->view->valor_mes as $key => $value) { ?>
                                <span class="currency float-left mr-1"></span>
                                <span class="count">
                                    <?php echo $value['qt_cliente_mes'] ?>
                                </span>
                        </h3>
                        <p class="text-light mt-1 m-0">Clientes Mês:
                            <?php //echo $value['mes'];
                                echo utf8_encode(gmstrftime('%B de %Y'));
                            ?>
                        </p>
                    </div>
                <?php } ?>
                <div class="card-right float-right text-right">
                    <i class="icon fade-5 icon-md pe-7s-users"></i>
                </div><!-- /.card-right -->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-body shadow bg-light rounded mb-1 mt-2">
    <div class="card-header bg-light">
        <h6>Delivery:
            <?php
            echo utf8_encode(gmstrftime('%d de %B de %Y'));
            ?>
        </h6>
    </div>
    <div class="data-table-area mt-3">
        <div class="data-table-list bg-light rounded">
            <div class="table-responsive">
                <table class="table table-sm table-responsive-sm text-center table-hover">
                    <thead>
                        <tr>
                            <th class="th-td-custom shadow-sm" scope="col">Lojas</th>
                            <th class="th-td-custom shadow-sm" scope="col">Valor</th>
                            <th class="th-td-custom shadow-sm" scope=" col">Média</th>
                            <th class="th-td-custom shadow-sm" scope="col">Pedidos</th>
                            <th class="th-td-custom shadow-sm" scope="col">Clientes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->valor_dia_atual_lojas as $key => $value) { ?>
                            <tr>
                                <th class="th-td-custom" scope="row"><?php echo $value['local'] ?></th>
                                <td class="text-success th-td-custom">R$
                                    <?php
                                    $valor_dia_atual = str_replace(".", ",",  $value['valor_dia_atual']);
                                    if (strlen($valor_dia_atual) < 7) {
                                        echo $valor_dia_atual;
                                    } else if (strlen($valor_dia_atual) <= 9) {
                                        echo substr_replace($valor_dia_atual, '.', -6, 0);
                                    } else if (strlen($valor_dia_atual) > 9) {
                                        $val_dia_atl = substr_replace($valor_dia_atual, '.', -6, 0);
                                        echo substr_replace($val_dia_atl, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td class="text-success th-td-custom">R$
                                    <?php
                                    $media_dia_atual = str_replace(".", ",",  $value['media_dia_atual']);
                                    if (strlen($media_dia_atual) < 7) {
                                        echo $media_dia_atual;
                                    } else if (strlen($media_dia_atual) <= 9) {
                                        echo substr_replace($media_dia_atual, '.', -6, 0);
                                    } else if (strlen($media_dia_atual) > 9) {
                                        $med_dia_atl = substr_replace($media_dia_atual, '.', -6, 0);
                                        echo substr_replace($med_dia_atl, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td class="text-success th-td-custom count"><?php echo $value['qt_pedido_dia_atual'] ?></td>
                                <td class="text-success th-td-custom count"><?php echo $value['qt_cliente_dia_atual'] ?></td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row mt-2">
    <!-- Grafico 1 -->
    <div class="col-xl-6 col-md-12 col-sm-12 mt-2">
        <div class="card mb-2 shadow">
            <div class="card-header">
                <i class="fas fa-chart-bar mr-1"></i>
                Flash:
                <?php
                echo utf8_encode(gmstrftime('%d de %B de %Y'));
                ?>
            </div>
            <script type="text/javascript">
                google.charts.load('current', {
                    packages: ['corechart', 'bar']
                });
                google.charts.setOnLoadCallback(drawAnnotations);

                function drawAnnotations() {
                    var data = google.visualization.arrayToDataTable([
                        ['Lojas', 'Valor', 'Média', 'Qtd. Pedidos'],
                    ]);

                    var data = google.visualization.arrayToDataTable([

                        ['Lojas', 'Valor', {
                                type: 'string',
                                role: 'annotation'
                            },
                            'Média', {
                                type: 'string',
                                role: 'annotation'
                            },
                            'Qtd. Pedidos', {
                                type: 'string',
                                role: 'annotation'
                            },


                        ],
                        ['', 0, '', 0, '', 0, ''],

                        <?php foreach ($this->view->valor_dia_atual_lojas as $key => $value) { ?>
                            <?php if (isset($key) != '') { ?>[
                                    "<?php echo $value['local']; ?>",
                                    "<?php echo $value['valor_dia_atual']; ?>",
                                    "<?php
                                        $valor_dia_atual = str_replace(".", ",",  $value['valor_dia_atual']);
                                        if (strlen($valor_dia_atual) < 7) {
                                            echo $valor_dia_atual;
                                        } else if (strlen($valor_dia_atual) <= 9) {
                                            echo substr_replace($valor_dia_atual, '.', -6, 0);
                                        } else if (strlen($valor_dia_atual) > 9) {
                                            $val_dia_atual = substr_replace($valor_dia_atual, '.', -6, 0);
                                            echo substr_replace($val_dia_atual, '.', -10, 0);
                                        }
                                        ?>",

                                    "<?php echo $value['media_dia_atual']; ?>",
                                    "<?php
                                        $media_dia_atual = str_replace(".", ",",  $value['media_dia_atual']);
                                        if (strlen($media_dia_atual) < 7) {
                                            echo $media_dia_atual;
                                        } else if (strlen($media_dia_atual) <= 9) {
                                            echo substr_replace($media_dia_atual, '.', -6, 0);
                                        } else if (strlen($media_dia_atual) > 9) {
                                            $med_dia_atual = substr_replace($media_dia_atual, '.', -6, 0);
                                            echo substr_replace($med_dia_atual, '.', -10, 0);
                                        }
                                        ?>",
                                    "<?php echo $value['qt_pedido_dia_atual']; ?>",
                                    "<?php echo (int)$value['qt_pedido_dia_atual']; ?>"
                                ],

                            <?php } ?>
                        <?php } ?>

                    ]);

                    var options = {
                        title: 'Flash',
                        colors: ['#28a745', '#007bff', '#f3ef7a'],
                        bar: {
                            groupWidth: "100%"
                        },
                        chartArea: {
                            width: '70%'
                        },
                        annotations: {
                            alwaysOutside: false,
                            textStyle: {
                                fontSize: 15,
                                auraColor: '#fff',
                                color: '#555'
                            },
                            boxStyle: {
                                stroke: '#ccc',
                                strokeWidth: 0,
                                gradient: {
                                    color1: '#f3e5f5',
                                    color2: '#f3e5f5',
                                    x1: '0%',
                                    y1: '0%',
                                    x2: '100%',
                                    y2: '100%'
                                }
                            }
                        },
                        hAxis: {
                            title: 'Total Valores',
                            format: 'decimal',
                            minValue: 0
                        },
                        legend: {
                            position: 'top',
                            maxLines: 3
                        },
                        vAxis: {
                            title: 'Lojas'
                        }
                    };
                    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
                    chart.draw(data, options);
                }
            </script>

            <div class="card-body pull-right">
                <div id="chart_div" class="pull-right mr-5" style="width: 90%; height: 400px;"></div>
            </div>
        </div>
    </div>

    <!-- Grafico 2 -->
    <div class="col-xl-6 col-md-12 col-sm-12 mt-2">
        <div class="card mb-2 shadow">
            <div class="card-header">
                <i class="fas fa-chart-pie mr-1"></i>
                Participação:
                <?php
                echo utf8_encode(gmstrftime('%d de %B de %Y'));
                ?>
            </div>
            <script type="text/javascript">
                google.charts.load("current", {
                    packages: ["corechart"]
                });
                google.charts.setOnLoadCallback(drawChart);

                function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                        ['Task', 'Hours per Day'],

                        <?php foreach ($this->view->valor_dia_atual_lojas as $key => $value) { ?>
                            <?php if (isset($key) != '') { ?>["<?php echo $value['local']; ?>", <?php echo (int)$value['valor_dia_atual']; ?>],

                            <?php } ?>
                        <?php } ?>

                    ]);

                    var options = {
                        title: 'Participação Lojas',
                        is3D: true,
                    };

                    var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
                    chart.draw(data, options);
                }
            </script>
            <div class="card-body pull-right">
                <div id="piechart_3d" class="pull-right" style="width: 100%; height: 400px;"></div>
            </div>
        </div>
        <div class="row col-md-3 col-sm-3 m-3 float-right">
            <button class="btn btn-sm btn-outline-dark float-right shadow-sm rounded-pill" onclick="window.print()"><i class="fa fa-print"></i> Imprimir</button>
        </div>
    </div>
</div>