<ol class="breadcrumb mb-2 mt-2">
    <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
    <li class="breadcrumb-item active">Pedidos</li>
</ol>

<div class="card-body shadow bg-light rounded mb-2">
    <div class="card-header bg-light">
        <a href="/cad_pedido" class="m-2 btn btn-sm btn-success float-right shadow-sm rounded-pill" data-toggle="tooltip" data-placement="top" title="Criar Novo Pedido"><i class="fa fa-plus-circle"></i> Novo Pedido</a>
        <h4>Pedidos </h4>
    </div>
    <div class="data-table-area mt-3">
        <div class="data-table-list bg-light rounded">
            <div class="table-responsive">
                <table class="bg-light table table-sm table-responsive-sm table-hover rounded data-table" id="data-table-basic">
                    <thead class="">
                        <tr>
                            <th scope="col">Nº Pedido</th>
                            <th scope="col">Nome Cliente</th>
                            <th scope="col">CPF</th>
                            <th scope="col">Loja</th>
                            <th scope="col">Status</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Data Pedido</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>


                    <tbody>
                        <?php foreach ($this->view->dados as $key => $value) { ?>
                            <tr class="">

                                <th scope="row"><?php echo $value['numero_pedido'] ?></th>
                                <td style="text-transform: uppercase;"><?php echo $value['nome'] ?></td>
                                <td><?php echo $value['cpf'] ?></td>
                                <td style="text-transform: uppercase;"><?php echo $value['local'] ?></td>

                                <?php if ($value['descricao'] == 'REALIZADO') { ?>
                                    <td class="text-info"><?php echo $value['descricao'] ?></td>
                                <?php } else if ($value['descricao'] == 'NOVO') { ?>
                                    <td class="text-success"><?php echo $value['descricao'] ?></td>
                                <?php } elseif ($value['descricao'] == 'EM PROCESSAMENTO') { ?>
                                    <td class="text-warning"><?php echo $value['descricao'] ?></td>

                                <?php } elseif ($value['descricao'] == 'NÃO FINALIZADO') { ?>
                                    <td class="text-danger"><?php echo $value['descricao'] ?></td>
                                <?php } ?>
                                <td>R$
                                    <?php
                                    $valor = str_replace(".", ",",  $value['valor']);
                                    if (strlen($valor) < 7) {
                                        echo $valor;
                                    } else if (strlen($valor) <= 9) {
                                        echo substr_replace($valor, '.', -6, 0);
                                    } else if (strlen($valor) > 9) {
                                        $valor_ped = substr_replace($valor, '.', -6, 0);
                                        echo substr_replace($valor_ped, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td><?php echo $value['data_criacao'] ?></td>
                                <td><a href="/detalhe_pedido?numero_pedido=<?php echo $value['numero_pedido'] ?>" class="btn btn-blue btn-sm shadow-sm rounded-pill" data-toggle="tooltip" data-placement="top" title="Visualizar Pedido"><i class=""></i>Abrir</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

</script>