    <?php
    $data_inicial = $_GET['data_inicial'];
    $data_final = $_GET['data_final'];
    ?>

    <ol class="breadcrumb mb-2 mt-2">
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>

    <div class="col-md-12 col-sm-12 p-2 mb-2 shadow-sm bg-light rounded">
        <div class="col-md-5 col-sm-5">
            <h4>Filtro</h4>
        </div>

        <form id="form" action="/search_home" method="get">

            <div class="form-row">
                <div class="form-group col-md-3 col-sm-3">
                    <label for="validationCustom01">Data Inicial</label>
                    <input name="data_inicial" value="" type="date" class="form-control form-control-sm rounded-pill" required>
                </div>
                <div class="form-group col-md-3 col-sm-3">
                    <label for="validationCustom02">Data Final</label>
                    <input name="data_final" value="" type="date" class="form-control form-control-sm rounded-pill" required>
                </div>
                <div class="form-group col-md-2 col-sm-2">
                    <div id="select_loja" style="display: block;">
                        <label for="validationCustom03">Loja </label>
                        <select name="id_loja" class="custom-select custom-select-sm rounded-pill">
                            <option value="">...</option>
                            <?php foreach ($this->view->lista_loja as $key => $value) { ?>
                                <option value="<?php echo $value['id'] ?>"><?php echo $value['local'] ?></option>
                            <?php } ?>
                        </select>
                        <div class="valid-feedback">
                            Tudo certo!
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-2 col-sm-2">
                    <div class="form-check form-check-sm">
                        <div class="onoff">
                            <h6>Todas as Lojas</h6>
                            <input type="checkbox" class="toggle" id="onoff1" onclick="mostrar('select_loja')" />
                            <label for="onoff1"></label>
                        </div>

                    </div>
                </div>
                <div class="col-md-2 col-sm-2">
                    <label>
                        <h6></h6>
                        <button class="btn btn-sm btn-outline-success shadow-sm rounded-pill" type="submit"><a class="fa fa-check"></a> Aplicar Filtro</button>
                    </label>
                </div>
            </div>
        </form>
    </div>

    <div class="col-md-12 col-sm-12 mb-2 p-2 rounded bg-light">
        <div class="row mt-3">
            <div class="col-lg-3 col-md-6">
                <div class="card shadow mb-1 border-left-01">
                    <div class="card-body">
                        <div class="stat-widget-five">
                            <div class="stat-icon flat-color-1">
                                <i class="pe-7s-cash"></i>
                            </div>
                            <div class="stat-content">
                                <div class="text-left">
                                    <div class="stat-text">R$
                                        <span>
                                            <?php foreach ($this->view->dados_filtro as $key => $value) { ?>
                                                <?php
                                                $valor_mes_atual = str_replace(".", ",",  $value['valor_mes_atual']);
                                                if (strlen($valor_mes_atual) < 7) {
                                                    echo $valor_mes_atual;
                                                } else if (strlen($valor_mes_atual) <= 9) {
                                                    echo substr_replace($valor_mes_atual, '.', -6, 0);
                                                } else if (strlen($valor_mes_atual) > 9) {
                                                    $valor = substr_replace($valor_mes_atual, '.', -6, 0);
                                                    echo substr_replace($valor, '.', -10, 0);
                                                }
                                                ?>
                                            <?php } ?>
                                        </span>
                                    </div>
                                    <div class="stat-heading">Valor: <?php echo date('d/m/Y', strtotime($data_inicial))  ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card shadow mb-1 border-left-02">
                    <div class="card-body">
                        <div class="stat-widget-five">
                            <div class="stat-icon flat-color-2">
                                <i class="pe-7s-cart"></i>
                            </div>
                            <div class="stat-content">
                                <div class="text-left">
                                    <div class="stat-text">
                                        <span class="count">
                                            <?php foreach ($this->view->dados_filtro as $key => $value) { ?>
                                                <?php echo $value['qt_pedido_mes_atual'] ?>
                                            <?php } ?>
                                        </span>
                                    </div>
                                    <div class="stat-heading">Pedidos <?php echo date('d/m/Y', strtotime($data_inicial))  ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card shadow mb-1 border-left-03">
                    <div class="card-body">
                        <div class="stat-widget-five">
                            <div class="stat-icon flat-color-1">
                                <i class="ti-money"></i>
                            </div>
                            <div class="stat-content">
                                <div class="text-left">
                                    <div class="stat-text">R$
                                        <span>
                                            <?php foreach ($this->view->dados_filtro as $key => $value) { ?>
                                                <?php
                                                $media_mes_atual = str_replace(".", ",",  $value['media_mes_atual']);
                                                if (strlen($media_mes_atual) < 7) {
                                                    echo $media_mes_atual;
                                                } else if (strlen($media_mes_atual) <= 9) {
                                                    echo substr_replace($media_mes_atual, '.', -6, 0);
                                                } else if (strlen($media_mes_atual) > 9) {
                                                    $valor_med = substr_replace($media_mes_atual, '.', -6, 0);
                                                    echo substr_replace($valor_med, '.', -10, 0);
                                                }
                                                ?>
                                            <?php } ?>
                                        </span>
                                    </div>
                                    <div class="stat-heading"> Média: <?php echo date('d/m/Y', strtotime($data_inicial))  ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card shadow mb-1 border-left-04">
                    <div class="card-body">
                        <div class="stat-widget-five">
                            <div class="stat-icon flat-color-4">
                                <i class="pe-7s-users"></i>
                            </div>
                            <div class="stat-content">
                                <div class="text-left">
                                    <div class="stat-text"><span class="count">
                                            <?php foreach ($this->view->dados_filtro as $key => $value) { ?>
                                                <?php echo $value['cliente_data_filtro'] ?>
                                            <?php } ?>
                                        </span></div>
                                    <div class="stat-heading">Clientes: <?php echo date('d/m/Y', strtotime($data_inicial))  ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?> </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-lg-3 col-md-6">
                <div class="card text-white bg-flat-color-1 shadow mb-1">
                    <div class="card-body">
                        <?php foreach ($this->view->valor_ano_filtro as $key => $value) { ?>
                            <div class="card-left pt-1 float-left">
                                <h3 class="mb-0 fw-r">
                                    <span class="currency float-left mr-1">$</span>
                                    <span>
                                        <?php
                                        $valor_ano_atual = str_replace(".", ",",  $value['valor_ano_atual']);
                                        if (strlen($valor_mes_atual) < 7) {
                                            echo $valor_ano_atual;
                                        } else if (strlen($valor_ano_atual) <= 9) {
                                            echo substr_replace($valor_ano_atual, '.', -6, 0);
                                        } else if (strlen($valor_ano_atual) > 9) {
                                            $valor_ano = substr_replace($valor_ano_atual, '.', -6, 0);
                                            echo substr_replace($valor_ano, '.', -10, 0);
                                        }
                                        ?>
                                    </span>
                                </h3>
                                <p class="text-light mt-1 m-0">Valor Ano: <?php echo $value['data_criacao'] ?></p>
                            </div>
                        <?php } ?> <div class="card-right float-right text-right">
                            <i class="icon fade-5 icon-md pe-7s-cash"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="card text-white bg-flat-color-2 shadow mb-1">
                    <div class="card-body">
                        <?php foreach ($this->view->valor_ano_filtro as $key => $value) { ?>
                            <div class="card-left pt-1 float-left">
                                <h3 class="mb-0 fw-r">
                                    <span class="currency float-left mr-1"></span>
                                    <span class="count">
                                        <?php echo $value['qt_pedido_ano_atual'] ?>
                                    </span>
                                </h3>
                                <p class="text-light mt-1 m-0">Pedidos Ano: <?php echo $value['data_criacao'] ?></p>
                            </div>
                        <?php } ?>
                        <div class="card-right float-right text-right">
                            <i class="icon fade-5 icon-md pe-7s-cart"></i>
                        </div><!-- /.card-right -->
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="card text-white bg-flat-color-3 shadow mb-1">
                    <div class="card-body">
                        <div class="card-left pt-1 float-left">
                            <?php foreach ($this->view->valor_ano_filtro as $key => $value) { ?>
                                <h3 class="mb-0 fw-r">
                                    <span class="currency float-left mr-1">$</span>
                                    <span>
                                        <?php
                                        $media_ano_atual = str_replace(".", ",",  $value['media_ano_atual']);
                                        if (strlen($media_ano_atual) < 7) {
                                            echo $media_ano_atual;
                                        } else if (strlen($media_ano_atual) <= 9) {
                                            echo substr_replace($media_ano_atual, '.', -6, 0);
                                        } else if (strlen($media_ano_atual) > 9) {
                                            $med_ano = substr_replace($media_ano_atual, '.', -6, 0);
                                            echo substr_replace($med_ano, '.', -10, 0);
                                        }
                                        ?>
                                    </span>
                                </h3>
                                <p class="text-light mt-1 m-0">Média Ano: <?php echo $value['data_criacao'] ?></p>
                        </div>
                    <?php } ?>
                    <div class="card-right float-right text-right">
                        <i class="icon fade-5 icon-md ti-money"></i>
                    </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="card text-white bg-flat-color-4 shadow mb-1">
                    <div class="card-body">
                        <div class="card-left pt-1 float-left">
                            <h3 class="mb-0 fw-r">
                                <?php foreach ($this->view->valor_ano_filtro as $key => $value) { ?>
                                    <span class="currency float-left mr-1"></span>
                                    <span class="count">
                                        <?php echo $value['cliente_ano'] ?>
                                    </span>
                            </h3>
                            <p class="text-light mt-1 m-0">Clientes Ano: <?php echo $value['data_criacao'] ?></p>
                        </div>
                    <?php } ?>
                    <div class="card-right float-right text-right">
                        <i class="icon fade-5 icon-md pe-7s-users"></i>
                    </div><!-- /.card-right -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body shadow bg-light rounded mt-4">
        <div class="card-header bg-light">
            <h6>Delivery - Loja: Todas - <?php echo date('d/m/Y', strtotime($data_inicial)) ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?></h6>
        </div>
        <div class="data-table-area mt-3">
            <div class="data-table-list bg-light rounded">

                <table class="table table-sm table-responsive-sm text-center table-hover mt-4">
                    <thead>
                        <tr>
                            <th class="th-td-custom shadow-sm" scope="col">Lojas</th>
                            <th class="th-td-custom shadow-sm" scope="col">Valor</th>
                            <th class="th-td-custom shadow-sm" scope="col">Média</th>
                            <th class="th-td-custom shadow-sm" scope="col">Qtd.Pedido</th>
                            <th class="th-td-custom shadow-sm" scope="col">Clientes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->search_home_full as $key => $value) { ?>
                            <tr>
                                <th class="th-td-custom" scope="row"><?php echo $value['local'] ?></th>
                                <td class="text-success th-td-custom">R$
                                    <?php
                                    $valor_data_filtro = str_replace(".", ",",  $value['valor_data_filtro']);
                                    if (strlen($valor_data_filtro) < 7) {
                                        echo $valor_data_filtro;
                                    } else if (strlen($valor_data_filtro) <= 9) {
                                        echo substr_replace($valor_data_filtro, '.', -6, 0);
                                    } else if (strlen($valor_data_filtro) > 9) {
                                        $valor_data_filt = substr_replace($valor_data_filtro, '.', -6, 0);
                                        echo substr_replace($valor_data_filt, '.', -10, 0);
                                    }
                                    ?>

                                </td>
                                <td class="text-success th-td-custom">R$
                                    <?php
                                    $media_data_filtro = str_replace(".", ",",  $value['media_data_filtro']);
                                    if (strlen($media_data_filtro) < 7) {
                                        echo $media_data_filtro;
                                    } else if (strlen($media_data_filtro) <= 9) {
                                        echo substr_replace($media_data_filtro, '.', -6, 0);
                                    } else if (strlen($media_data_filtro) > 9) {
                                        $med_data_filt = substr_replace($media_data_filtro, '.', -6, 0);
                                        echo substr_replace($med_data_filt, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td class="text-success th-td-custom count">
                                    <?php echo $value['qt_pedido_data_filtro'] ?>
                                </td>
                                <td class="text-success th-td-custom count">
                                    <?php echo $value['qt_cliente_data_filtro'] ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

                <table class="table table-sm table-responsive-sm text-center table-hover mt-4">
                    <h6>Total Lojas</h6>
                    <thead class="">
                        <tr class="">
                            <th class="th-td-custom shadow-sm" scope="col">Lojas</th>
                            <th class="th-td-custom shadow-sm" scope="col">Valor Total</th>
                            <th class="th-td-custom shadow-sm" scope="col">Média</th>
                            <th class="th-td-custom shadow-sm" scope="col">Total de Pedidos</th>
                            <th class="th-td-custom shadow-sm" scope="col">Total de Clientes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->valor_total_lojas as $key => $value) { ?>
                            <tr>
                                <th class="th-td-custom shadow-sm" scope="row">Todas</th>
                                <td class="text-success th-td-custom shadow-sm">R$
                                    <?php
                                    $valor_data_filtro = str_replace(".", ",",  $value['valor_data_filtro']);
                                    if (strlen($valor_data_filtro) < 7) {
                                        echo $valor_data_filtro;
                                    } else if (strlen($valor_data_filtro) <= 9) {
                                        echo substr_replace($valor_data_filtro, '.', -6, 0);
                                    } else if (strlen($valor_data_filtro) > 9) {
                                        $valor_filt = substr_replace($valor_data_filtro, '.', -6, 0);
                                        echo substr_replace($valor_filt, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td class="text-success th-td-custom shadow-sm">R$
                                    <?php
                                    $media_data_filtro = str_replace(".", ",",  $value['media_data_filtro']);
                                    if (strlen($media_data_filtro) < 7) {
                                        echo $media_data_filtro;
                                    } else if (strlen($media_data_filtro) <= 9) {
                                        echo substr_replace($media_data_filtro, '.', -6, 0);
                                    } else if (strlen($media_data_filtro) > 9) {
                                        $med_filt = substr_replace($media_data_filtro, '.', -6, 0);
                                        echo substr_replace($med_filt, '.', -10, 0);
                                    }
                                    ?>
                                </td>
                                <td class="text-success th-td-custom shadow-sm count"><?php echo $value['qt_pedido_data_filtro'] ?></td>
                                <td class="text-success th-td-custom shadow-sm count"><?php echo $value['qt_cliente_data_filtro'] ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="row mt-4 quebra_pagina">
        <!-- Grafico 1 -->
        <div class="col-xl-6 col-md-12 col-sm-12 mt-2">
            <div class="card mb-2 shadow">
                <div class="card-header">
                    <i class="fas fa-chart-bar mr-1"></i>
                    Flash - <?php echo date('d/m/Y', strtotime($data_inicial)) ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?>
                </div>
                <script type="text/javascript">
                    google.charts.load('current', {
                        packages: ['corechart', 'bar']
                    });
                    google.charts.setOnLoadCallback(drawAnnotations);


                    function drawAnnotations() {

                        var data = google.visualization.arrayToDataTable([
                            ['Lojas', 'Valor', 'Média', 'Qtd. Pedidos'],
                        ]);

                        var data = google.visualization.arrayToDataTable([
                            ['Lojas', 'Valor', {
                                    type: 'string',
                                    role: 'annotation'

                                },
                                'Média', {
                                    type: 'string',
                                    role: 'annotation'
                                },
                                'Qtd. Pedidos', {
                                    type: 'string',
                                    role: 'annotation'
                                }
                            ],
                            ['', 0, '', 0, '', 0, ''],

                            <?php foreach ($this->view->search_home_full as $key => $value) { ?>
                                <?php if (isset($key) != '') { ?>[
                                        "<?php echo $value['local']; ?>",
                                        "<?php echo $value['valor_data_filtro']; ?>",
                                        "<?php
                                            $valor_data_filtro = str_replace(".", ",",  $value['valor_data_filtro']);
                                            if (strlen($valor_data_filtro) < 7) {
                                                echo $valor_data_filtro;
                                            } else if (strlen($valor_data_filtro) <= 9) {
                                                echo substr_replace($valor_data_filtro, '.', -6, 0);
                                            } else if (strlen($valor_data_filtro) > 9) {
                                                $valor_filt = substr_replace($valor_data_filtro, '.', -6, 0);
                                                echo substr_replace($valor_filt, '.', -10, 0);
                                            }
                                            ?>",

                                        "<?php echo $value['media_data_filtro']; ?>",
                                        "<?php
                                            $media_data_filtro = str_replace(".", ",",  $value['media_data_filtro']);
                                            if (strlen($media_data_filtro) < 7) {
                                                echo $media_data_filtro;
                                            } else if (strlen($media_data_filtro) <= 9) {
                                                echo substr_replace($media_data_filtro, '.', -6, 0);
                                            } else if (strlen($media_data_filtro) > 9) {
                                                $med_filt = substr_replace($media_data_filtro, '.', -6, 0);
                                                echo substr_replace($med_filt, '.', -10, 0);
                                            }
                                            ?>",
                                        "<?php echo $value['qt_pedido_data_filtro']; ?>",
                                        "<?php echo (int)$value['qt_pedido_data_filtro']; ?>"
                                    ],

                                <?php } ?>
                            <?php } ?>

                        ]);




                        var options = {
                            title: 'Flash',
                            colors: ['#28a745', '#007bff', '#f3ef7a'],
                            bar: {
                                groupWidth: "100%"
                            },
                            chartArea: {
                                width: '70%'
                            },
                            annotations: {
                                alwaysOutside: false,
                                textStyle: {
                                    fontSize: 15,
                                    auraColor: '#fff',
                                    color: '#555'
                                },
                                boxStyle: {
                                    stroke: '#ccc',
                                    strokeWidth: 0,
                                    gradient: {
                                        color1: '#f3e5f5',
                                        color2: '#f3e5f5',
                                        x1: '0%',
                                        y1: '0%',
                                        x2: '100%',
                                        y2: '100%'
                                    }
                                }
                            },
                            hAxis: {
                                title: 'Total Valores',
                                format: 'decimal',
                                minValue: 0
                            },
                            legend: {
                                position: 'top',
                                maxLines: 3
                            },
                            vAxis: {
                                title: 'Lojas'
                            }
                        };
                        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
                        chart.draw(data, options);
                    }
                </script>

                <div class="card-body pull-right">
                    <div id="chart_div" class="pull-right mr-5" style="width: 90%; height: 400px;"></div>
                </div>
            </div>
        </div>

        <!-- Grafico 2 -->
        <div class="col-xl-6 col-md-12 col-sm-12 mt-2">
            <div class="card mb-2 shadow">
                <div class="card-header">
                    <i class="fas fa-chart-pie mr-1"></i>
                    Participação Lojas - <?php echo date('d/m/Y', strtotime($data_inicial)) ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?>
                </div>
                <script type="text/javascript">
                    google.charts.load("current", {
                        packages: ["corechart"]
                    });
                    google.charts.setOnLoadCallback(drawChart);

                    function drawChart() {
                        var data = google.visualization.arrayToDataTable([
                            ['Task', 'Hours per Day'],

                            <?php foreach ($this->view->search_home_full as $key => $value) { ?>
                                <?php if (isset($key) != '') { ?>["<?php echo $value['local']; ?>", <?php echo (int)$value['valor_data_filtro']; ?>],

                                <?php } ?>
                            <?php } ?>

                        ]);

                        var options = {
                            title: 'Participação Lojas',
                            is3D: true,
                        };

                        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
                        chart.draw(data, options);
                    }
                </script>
                <div class="card-body pull-right">
                    <div id="piechart_3d" class="pull-right" style="width: 100%; height: 400px;"></div>
                </div>
            </div>
            <div class="row col-md-3 col-sm-3 m-3 float-right">
                <button class="btn btn-sm btn-outline-dark float-right shadow-sm rounded-pill" onclick="window.print()"><i class="fa fa-print"></i> Imprimir</button>
            </div>
        </div>
    </div>