<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>

<div class="col-md-12 col-sm-12 p-2 mb-4 shadow bg-light rounded">
    <div class="col-md-5 col-sm-5">
        <h4>Filtro</h4>
    </div>

    <form id="form" action="/search_home" method="get">

        <div class="form-row">
            <div class="form-group col-md-3 col-sm-3">
                <label for="validationCustom01">Data Inicial</label>
                <input name="data_inicial" value="" type="date" class="form-control form-control-sm rounded-pill" required>
            </div>
            <div class="form-group col-md-3 col-sm-3">
                <label for="validationCustom02">Data Final</label>
                <input name="data_final" value="" type="date" class="form-control form-control-sm rounded-pill" required>
            </div>
            <div class="form-group col-md-2 col-sm-2">
                <div id="select_loja" style="display: block;">
                    <label for="validationCustom03">Loja </label>
                    <select name="id_loja" class="custom-select custom-select-sm rounded-pill">
                        <option value="">...</option>
                        <?php foreach ($this->view->lista_loja as $key => $value) { ?>
                            <option value="<?php echo $value['id'] ?>"><?php echo $value['local'] ?></option>
                        <?php } ?>
                    </select>
                    <div class="valid-feedback">
                        Tudo certo!
                    </div>
                </div>
            </div>
            <div class="form-group col-md-2 col-sm-2">
                <div class="form-check form-check-sm">
                    <div class="onoff">
                        <h6>Todas as Lojas</h6>
                        <input type="checkbox" class="toggle" id="onoff1" onclick="mostrar('select_loja')" />
                        <label for="onoff1"></label>
                    </div>

                </div>
            </div>
            <div class="col-md-2 col-sm-2">
                <label>
                    <h6></h6>
                    <button class="btn btn-sm btn-outline-success shadow rounded-pill" type="submit"><a class="fa fa-check"></a> Aplicar Filtro</button>
                </label>
            </div>
        </div>
    </form>
</div>

    <div class="card shadow bg-light rounded mb-4">
        <div class="card-header">
            <?php
            $data_inicial = $_GET['data_inicial'];
            $data_final = $_GET['data_final'];
            ?>
            <div class="col-md-10 col-sm-10">
                <h3 class="text-info">Loja: <?php echo $this->view->search_home[0]['local'] ?> - Delivery - <?php echo date('d/m/Y', strtotime($data_inicial)) ?> a <?php echo date('d/m/Y', strtotime($data_final)) ?></h4>
            </div>
            <table class="table table-sm table-responsive-sm text-center table-hover">
                <thead>
                    <tr>
                        <th scope="col">Lojas</th>
                        <th scope="col">Valor</th>
                        <th scope="col">Média</th>
                        <th scope="col">Qtd.Pedidos</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->search_home as $key => $value) { ?>
                        <tr>
                            <th scope="row"><?php echo $value['local'] ?></th>
                            <td>R$
                            <?php
                                        $valor_data_filtro = str_replace(".", ",",  $value['valor_data_filtro']);
                                        if (strlen($valor_data_filtro) < 7) {
                                            echo $valor_data_filtro;
                                                        
                                        } else if (strlen($valor_data_filtro) <= 9){
                                            echo substr_replace($valor_data_filtro, '.', -6, 0);

                                        } else if (strlen($valor_data_filtro) > 9) {
                                            $val_filt= substr_replace($valor_data_filtro, '.', -6, 0);
                                            echo substr_replace($val_filt, '.', -10 , 0);
                                        }
                                    ?>
                            </td>
                            <td>R$
                            <?php
                                        $media_data_filtro = str_replace(".", ",",  $value['media_data_filtro']);
                                        if (strlen($media_data_filtro) < 7) {
                                            echo $media_data_filtro;
                                                        
                                        } else if (strlen($media_data_filtro) <= 9){
                                            echo substr_replace($media_data_filtro, '.', -6, 0);

                                        } else if (strlen($media_data_filtro) > 9) {
                                            $med_filt= substr_replace($media_data_filtro, '.', -6, 0);
                                            echo substr_replace($med_filt, '.', -10 , 0);
                                        }
                                    ?>
                            </td>
                            <td><?php echo $value['qt_pedido_data_filtro'] ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <div class="card-body">

            <script type="text/javascript">
                google.charts.load('current', {
                    packages: ['corechart', 'bar']
                });
                google.charts.setOnLoadCallback(drawAnnotations);

                function drawAnnotations() {
                    var data = google.visualization.arrayToDataTable([
                        ['Lojas', 'Valor', 'Média', 'Qtd. Pedidos'],
                    ]);

                    var data = google.visualization.arrayToDataTable([

                        ['Lojas', 'Valor', {
                                type: 'string',
                                role: 'annotation'
                            },
                            'Média', {
                                type: 'string',
                                role: 'annotation'
                            },
                            'Qtd. Pedidos', {
                                type: 'string',
                                role: 'annotation'
                            },


                        ],
                        ['', 0, '', 0, '', 0, ''],

                        <?php foreach ($this->view->search_home as $key => $value) { ?>
                            <?php if (isset($key) != '') { ?>[
                                    "<?php echo $value['local']; ?>",
                                    "<?php echo $value['valor_data_filtro']; ?>",
                                    " <?php
                                        $valor_data_filtro = str_replace(".", ",",  $value['valor_data_filtro']);
                                        if (strlen($valor_data_filtro) < 7) {
                                            echo $valor_data_filtro;
                                                        
                                        } else if (strlen($valor_data_filtro) <= 9){
                                            echo substr_replace($valor_data_filtro, '.', -6, 0);

                                        } else if (strlen($valor_data_filtro) > 9) {
                                            $val_data_filt= substr_replace($valor_data_filtro, '.', -6, 0);
                                            echo substr_replace($val_data_filt, '.', -10 , 0);
                                        }
                                    ?>",

                                    "<?php echo $value['media_data_filtro']; ?>",
                                    "<?php
                                        $media_data_filtro = str_replace(".", ",",  $value['media_data_filtro']);
                                        if (strlen($media_data_filtro) < 7) {
                                            echo $media_data_filtro;
                                                        
                                        } else if (strlen($media_data_filtro) <= 9){
                                            echo substr_replace($media_data_filtro, '.', -6, 0);

                                        } else if (strlen($media_data_filtro) > 9) {
                                            $med_data_filt= substr_replace($media_data_filtro, '.', -6, 0);
                                            echo substr_replace($med_data_filt, '.', -10 , 0);
                                        }
                                    ?>",
                                    "<?php echo $value['qt_pedido_data_filtro']; ?>",
                                    "<?php echo (int)$value['qt_pedido_data_filtro']; ?>"
                                ],

                            <?php } ?>
                        <?php } ?>

                    ]);

                   
                    var options = {
                            title: 'Flash',
                            colors: ['#007bff', '#f3ef7a', '#28a745'],
                            bar: {
                                groupWidth: "100%"
                            },
                            chartArea: {
                                width: '65%'
                            },
                            annotations: {
                                alwaysOutside: false,
                                textStyle: {
                                    fontSize: 15,
                                    auraColor: '#fff',
                                    color: '#555'
                                },
                                boxStyle: {
                                    stroke: '#ccc',
                                    strokeWidth: 0,
                                    gradient: {
                                        color1: '#f3e5f5',
                                        color2: '#f3e5f5',
                                        x1: '0%',
                                        y1: '0%',
                                        x2: '100%',
                                        y2: '100%'
                                    }
                                }
                            },
                            hAxis: {
                                title: 'Total Valores',
                                format: 'short',
                                minValue: 0
                            },
                            legend: {
                                position: 'top',
                                maxLines: 3
                            },
                            vAxis: {
                                title: 'Lojas'
                            }
                        };
                    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
                    chart.draw(data, options);
                }
            </script>
            <!-- grafico 1 -->



            <div class="card-body ">
                <div id="chart_div" class="" style="width: 90%; height: 400px;"></div>
            </div>



            <div class="row col-md-3 col-sm-3 m-3 float-right">
                <button class="btn btn-sm btn-outline-dark float-right" onclick="window.print()"><i class="fa fa-print"></i> Imprimir</button>
            </div>
        </div>
    </div>

