<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<link rel="icon" href="/images/favicon.ico" type="image/ico" />

	<title>App | Lista de Compras </title>
	<link href="css/styles.css" rel="stylesheet" />

	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">

	<!-- style tables CSS
		============================================ -->
	<link rel="stylesheet" href="css/tables.css">

	<!-- Data Table JS
		============================================ -->
	<link rel="stylesheet" href="/css/jquery.dataTables.min.css">

	<!-- Font Awesome
		============================================ -->
	<link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet">

	<!-- Icon pe-icon
		============================================ -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">

	<!-- summernote -->
	<link rel="stylesheet" href="/summernote/summernote-bs4.css">


	<script src="/js/jquery-3.1.1.slim.min.js"></script>
	<script src="js/data-table/jquery.dataTables.min.js"></script>

	<script src="/js/custom-js/script.js"></script>
	<script src="/js/charts.js"></script>

</head>

<body class="sb-nav-fixed">
	<?php
	//setlocale(LC_ALL, NULL);
	setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'pt_BR.UTF8', 'portuguese');
	date_default_timezone_set('America/Sao_Paulo');

	?>
	<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
		<a class="navbar-brand" href="/home">App | Lista de Compras</a>
		<button class="btn btn-link order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fa fa-bars"></i></button>
		<ul class="navbar-nav ml-auto ml-auto mr-0 mr-md-3 my-2 my-md-0 ">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span><?= $_SESSION['nome'] ?></span> <i class="fa fa-user fa-fw"></i></a>
				<div class="dropdown-menu dropdown-menu-right rounded-pill p-2" aria-labelledby="userDropdown">
					<a class="dropdown-item small" href="/sair">Sair <i class="fa fa-arrow-right"></i></a>
				</div>
			</li>
		</ul>
	</nav>
	<div id="layoutSidenav">
		<div id="layoutSidenav_nav">
			<nav class="sb-sidenav accordion sb-sidenav-dark shadow" id="sidenavAccordion">
				<div class="sb-sidenav-menu">
					<div class="nav">
						<div class="sb-sidenav-menu-heading">Core</div>
						<a class="nav-link" href="/home">
							<div class="sb-nav-link-icon"><i class="fa fa-laptop"></i></div>
							Dashboard
						</a>
						<div class="sb-sidenav-menu-heading">Menu</div>
						<nav class="sb-sidenav-menu-nested nav">
							<a class="nav-link" href="/cliente"><i class="mr-1 fa fa-user"></i> Clientes</a>
							<a class="nav-link" href="/listar_pedidos"><i class="mr-1 fa fa-shopping-cart"></i> Pedidos</a>
							<a class="nav-link" href="/lojas"><i class="mr-1 fa fa-list"></i> Lojas</a>
						</nav>
						<?php if ($_SESSION['id_tipo'] == 1) { ?>
							<div class="sb-sidenav-menu-heading">Tools</div>
							<nav class="sb-sidenav-menu-nested nav">
								<a class="nav-link" href="/usuarios">
									<div class="sb-nav-link-icon"><i class="fa fa-users"></i></div>
									Usuários
								</a>
								<a class="nav-link" href="/cadastro_user">
									<div class="sb-nav-link-icon"><i class="fa fa-user"></i></div>
									Cadastro Usuários
								</a>
								<a class="nav-link" href="/cadastro_cliente">
									<div class="sb-nav-link-icon"><i class="fa fa-user"></i></div>
									Cadastro Clientes
								</a>
								<a class="nav-link" href="/cadastro_loja">
									<div class="sb-nav-link-icon"><i class="fa fa-list"></i></div>
									Cadastro Lojas
								</a>
							</nav>
						<?php } ?>

					</div>
				</div>
				<div class="sb-sidenav-footer">
					<a class="small" href="/sair"> Sair <i class="fa fa-power-off"></i></a>
				</div>
			</nav>
		</div>
		<div class="cont" id="layoutSidenav_content">
			<main class="">
				<div class="container-fluid">
					<?= $this->content() ?>
				</div>
			</main>>
			<footer class="container p-3">
				<div class="d-flex justify-content-center">
					<ul class="nav social-icons ms-3">
					<li class="nav-item m-auto text-color">
							&copy; 2021 João F. Ramos
						</li>
						<li class="nav-item me-2 text-white">
							<a class="social-icon" href="https://linkedin.com/in/joao-f-ramos-04692070" target="_blank"><i class="ti-linkedin"></i></a>
						</li>
						<li class="nav-item me-2">
							<a class="social-icon" href="https://github.com/joaoramos1104" target="_blank"><i class="ti-github"></i></a>
						</li>
						<li class="nav-item me-2">
							<a class="social-icon" href="https://www.instagram.com/f.ramosjoao" target="_blank"><i class="ti-instagram"></i></a>
						</li>
					</ul>
				</div>
			</footer>
		</div>
	</div>
	<script src="/js/bootstrap.bundle.min.js"></script>
	<script src="/js/custom-js/scripts_ajax.js"></script>


	<!-- Data Table JS
		============================================ -->
	<script src="js/data-table/data-table-act.js"></script>


	<!-- Summernote -->
	<script src="/summernote/summernote-bs4.min.js"></script>
	<script>
		$(function() {
			// Summernote
			$('.textarea').summernote()
		})
	</script>

</body>

</html>